name: Deploy Storybook to GitHub Pages
on: [push]
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Storybook to GitHub Pages
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          path: 'storybook-static'
          build_command: "npm run storybook:build"

